/**
 * Resident-portal AI assistant (portal-wide Q&A).
 *
 * Answers are generated by a hosted chat model behind a small provider
 * abstraction:
 *   - `deepseek`    OpenAI-compatible chat completions (default).
 *   - `huggingface` Hugging Face Inference API chat completions.
 *
 * When the selected provider's API key (or required model) is not configured —
 * e.g. local dev before the key is provisioned — the assistant falls back to a
 * keyword matcher over the same knowledge base below, so the feature remains
 * usable and testable without external credentials.
 *
 * The assistant is informational only: it explains how the resident portal
 * works and where to find things, but never performs actions or changes data.
 *
 * Factual portal questions (e.g. "who is the current barangay captain?") are
 * answered from a live snapshot of the database (`buildPortalContext`) that is
 * injected into the system prompt at request time — and used by the keyword
 * fallback too — so answers reflect the actual barangay, officials, and
 * announcements rather than a static guide.
 */

import { Official } from '../models/official.model';
import { Barangay } from '../models/barangay.model';
import { Announcement } from '../models/announcement.model';

export type ChatbotMessage = {
  role: 'user' | 'assistant';
  content: string;
};

/** Cap on the persisted conversation length (oldest turns are dropped). */
export const CHATBOT_MAX_MESSAGES = 40;

/** Cap on a single user message (characters). */
export const CHATBOT_MAX_MESSAGE_LENGTH = 2000;

/**
 * Live snapshot of the portal data the assistant may be asked about. Built at
 * request time and injected into the model's system prompt; also used by the
 * no-key keyword fallback so both paths answer from the same facts.
 */
export interface PortalContext {
  barangay: {
    name: string;
    city: string;
    province: string;
    region: string;
    zipCode?: string;
    contactNumber?: string;
    emailAddress?: string;
    officeAddress?: string;
    officeHours?: string[];
    emergencyHotline?: string;
    emergencyMobile?: string;
  } | null;
  officials: Array<{
    fullName: string;
    designatedPosition: string;
    contactNumber?: string;
    officeLocation?: string;
  }>;
  announcements: Array<{ titleText: string; eventDate?: string }>;
}

/** Context used when nothing could be loaded (or the caller has no data). */
const EMPTY_CONTEXT: PortalContext = {
  barangay: null,
  officials: [],
  announcements: [],
};

/** Knowledge-base entry used by the no-key keyword fallback. */
interface KnowledgeEntry {
  /** Lowercase keyword fragments (English and Tagalog) that indicate the topic. */
  keywords: string[];
  answer: string;
  /** Tagalog answer; the fallback falls back to `answer` when absent. */
  answerTagalog?: string;
}

/**
 * Portal knowledge base — mirrors the resident sidebar (`ResidentSidebar`),
 * the resident help FAQ, and the request forms. Used by the keyword fallback;
 * the system prompt above carries the authoritative full guide for the hosted
 * model. Entries are ordered most-specific first because the scorer breaks
 * ties by keeping the earliest entry with the highest match count.
 */
const KNOWLEDGE_BASE: KnowledgeEntry[] = [
  {
    keywords: [
      'document', 'clearance', 'certificate', 'request document',
      'barangay clearance', 'certificate of residency', 'residency', 'indigency',
      'certificate of indigency', 'business permit', 'good moral', 'barangay id',
      'police clearance', 'document request', 'request ng dokumento',
      'kumuha ng clearance',
      'kumuha ng dokumento', 'paano kumuha', 'kumuha', 'kuha ng', 'hingi',
      'dokumento', 'katibayan', 'sertipiko', 'sertipikasyon', 'sedula',
      'requirements', 'requirement', 'kailangan', 'mga kailangan',
      'ano ang kailangan', 'kailangan para', 'fee', 'fees', 'bayad', 'magkano',
      'valid id', 'verification id', 'processing time', 'how long',
      'gaano katagal', 'ilan araw', 'kailan makukuha', 'turnaround',
    ],
    answer:
      'You can request documents under My Document Requests. Tap "Request Document", choose the type (Barangay Clearance, Certificate of Residency, Certificate of Indigency, Barangay Business Permit, Certificate of Good Moral Character, Barangay ID, or Other), choose the purpose, enter your contact number and email, and attach a photo of a valid (government-issued) ID. Processing takes about 2–3 business days and you will be contacted by phone or email; bring a valid ID when claiming at the barangay hall. Processing fees may apply as per barangay ordinance.',
    answerTagalog:
      'Puwede kang mag-request ng mga dokumento sa My Document Requests. I-tap ang "Request Document", piliin ang uri (Barangay Clearance, Certificate of Residency, Certificate of Indigency, Barangay Business Permit, Certificate of Good Moral Character, Barangay ID, o Other), piliin ang layunin, ilagay ang contact number at email, at mag-attach ng litrato ng valid (government-issued) ID. Mga 2–3 business days ang pagproseso at kokontakin ka sa telepono o email; magdala ng valid ID kapag kukunin ang dokumento sa barangay hall. Maaaring may bayad ayon sa ordinansa ng barangay.',
  },
  {
    keywords: [
      'status', 'track', 'tracking', 'ready for pickup', 'pick up', 'pickup',
      'my document', 'my request', 'status ng request', 'status ng report',
      'nasaan na', 'kailan ready', 'asensado',
    ],
    answer:
      'To track a request, open My Document Requests and select it — you will see its current status and timeline (Submitted, Processing, Ready for Pickup, Released, or Rejected). Incident reports are tracked the same way under My Incident Reports. Notifications also alerts you when a status changes.',
    answerTagalog:
      'Para i-track ang request, buksan ang My Document Requests at piliin ito — makikita mo ang kasalukuyang status at timeline (Submitted, Processing, Ready for Pickup, Released, o Rejected). Ganito rin i-track ang incident reports sa My Incident Reports. May alerto rin sa Notifications kapag nagbago ang status.',
  },
  {
    keywords: [
      'incident', 'incident report', 'report', 'sumbong', 'ireport', 'i-report',
      'mag-report', 'magreport', 'mag-file', 'filing', 'complaint', 'reklamo',
      'sunog', 'fire', 'baha', 'flood', 'sakuna', 'aksidente', 'accident',
      'gulo', 'nakawan', 'krimen', 'crime', 'domestic', 'disturbance',
      'infrastructure', 'evidence', 'ebidensiya', 'photo', 'video', 'larawan',
      'attach', 'upload', 'priority', 'triage', 'insidente',
      'new incident report', 'bagong insidente', 'mag-report ng insidente',
    ],
    answer:
      'To report an incident, open My Incident Reports and tap "New Incident Report". Choose the category (Fire, Flood, Medical Emergency, Criminal Activity, Road Accident, Domestic Dispute, Infrastructure Damage, Public Disturbance, or Other), describe what happened, and set the location on the map. You can attach photos or videos as evidence. The app assigns a triage priority automatically, and responders can open a Live Chat with you. Track progress in My Incident Reports.',
    answerTagalog:
      'Para mag-report ng insidente, buksan ang My Incident Reports at i-tap ang "New Incident Report". Piliin ang kategorya (Fire, Flood, Medical Emergency, Criminal Activity, Road Accident, Domestic Dispute, Infrastructure Damage, Public Disturbance, o Other), ilarawan ang nangyari, at itakda ang lokasyon sa mapa. Maaari kang mag-attach ng mga larawan o video bilang ebidensiya. Awtomatikong nagtatalaga ang app ng triage priority, at puwedeng magbukas ng Live Chat ang mga responder. Subaybayan ang progreso sa My Incident Reports.',
  },
  {
    keywords: [
      'emergency', 'emergency number', 'emergency hotline', 'emergency mobile',
      'emergency contact', 'hotline', 'saklolo', 'tumawag', 'tatawagan',
      'sino ang tatawagan', 'numero ng emergency', 'ambulance', 'police',
      'pulis', 'bumbero', 'tanod', '911',
    ],
    answer:
      'For an emergency, call the barangay emergency hotline or emergency mobile, or 911 for national emergency services (police, fire, ambulance). The barangay numbers are shown under Help & Support Center and in the "Current barangay information" section. For non-urgent concerns, file an incident report under My Incident Reports.',
    answerTagalog:
      'Sa emergency, tumawag sa emergency hotline o emergency mobile ng barangay, o sa 911 para sa national emergency services (pulis, bumbero, ambulansya). Nasa Help & Support Center ang mga numero ng barangay. Para sa hindi agarang usapin, mag-file ng incident report sa My Incident Reports.',
  },
  {
    keywords: [
      'official', 'officials', 'captain', 'punong barangay', 'kagawad',
      'konsehal', 'councilor', 'councilors', 'council', 'sk chairman',
      'sk chair', 'sk official', 'sangguniang kabataan', 'secretary', 'kalihim',
      'treasurer', 'ingat-yaman', 'directory', 'who is', 'opisyal', 'opisyales',
      'kapitan', 'kap', 'sino si', 'sinu-sino', 'namumuno', 'kasalukuyang kapitan',
    ],
    answer:
      'You can see the current Punong Barangay (Captain), Kagawad (council members), SK Chairman, Secretary, and Treasurer under Barangay Officials in the menu, together with office hours and emergency contacts.',
    answerTagalog:
      'Makikita mo ang kasalukuyang Punong Barangay (Kapitan), mga Kagawad, SK Chairman, Secretary, at Treasurer sa Barangay Officials sa menu, kasama ang office hours at emergency contacts.',
  },
  {
    keywords: [
      'office hours', 'oras ng opisina', 'operating hours', 'open', 'bukas',
      'bukas ba', 'kailan bukas', 'weekend', 'sabado', 'linggo', 'holiday',
      'location', 'address', 'where is', 'saan banda', 'saan ang barangay',
      'lugar', 'opisina', 'barangay hall', 'hall',
    ],
    answer:
      'The barangay hall is open on weekdays and usually half-day on Saturdays, and closed on Sundays and holidays. The exact office hours, address, and location are shown under Help & Support Center and Barangay Officials, and in the "Current barangay information" section.',
    answerTagalog:
      'Bukas ang barangay hall tuwing weekdays at kadalasan hanggang kalahating araw kapag Sabado, at sarado tuwing Linggo at holidays. Nasa Help & Support Center at Barangay Officials ang eksaktong office hours, address, at lokasyon.',
  },
  {
    keywords: [
      'barangay contact', 'contact the barangay', 'kontakin ang barangay',
      'tawagan ang barangay', 'barangay contact number',
      'contact number ng barangay', 'numero ng barangay', 'telepono ng barangay',
      'telephone ng barangay', 'landline', 'barangay email', 'email ng barangay',
      'email address ng barangay', 'official email', 'contact details ng barangay',
    ],
    answer:
      'You can reach the barangay through its contact number, email, and emergency hotline, shown under Help & Support Center and in the "Current barangay information" section.',
    answerTagalog:
      'Maaari mong kontakin ang barangay sa contact number, email, at emergency hotline nito, nasa Help & Support Center at sa "Current barangay information" section.',
  },
  {
    keywords: [
      'announcement', 'announcements', 'anunsyo', 'anunsiyo', 'mga anunsyo',
      'advisory', 'news', 'bulletin', 'abiso', 'pabatid', 'balita', 'ayuda',
      'relief', 'pamigay', 'vaccination', 'bakuna', 'medical mission',
      'libreng gamot', 'curfew', 'pulong', 'walang pasok',
      'suspendido ang klase', 'bagyo', 'program', 'notice', 'notices',
      'public notice',
    ],
    answer:
      'Barangay announcements, advisories, and programs (medical missions, vaccination, relief/ayuda distribution, curfew, class suspensions) are under Announcements in the menu. Open one to read the full post; the latest ones are also listed in the "Current barangay information" section.',
    answerTagalog:
      'Nasa Announcements sa menu ang mga anunsyo, abiso, at programa ng barangay (medical mission, bakuna, pamamahagi ng ayuda, curfew, walang pasok). Buksan ang isa para mabasa ang buong post; nakalista rin ang mga pinakabago sa "Current barangay information" section.',
  },
  {
    keywords: [
      'chat', 'live chat', 'chat sa staff', 'message', 'mensahe', 'mensahe sa admin',
      'responder', 'barangay staff', 'kausap', 'kausapin', 'makausap', 'makipag-chat',
      'mag-chat', 'admin',
    ],
    answer:
      'Live Chat lets you talk to barangay staff and responders about your requests and reports. A chat is started by barangay staff (after an incident or request) — you cannot open a new empty chat yourself. Once staff reply, the conversation appears under Live Chat in the menu, and you can reply there.',
    answerTagalog:
      'Ang Live Chat ay para makausap mo ang mga barangay staff at responder tungkol sa iyong mga request at report. Ang barangay staff ang nagbubukas ng chat (pagkatapos ng insidente o request) — hindi ka makakapagsimula ng bagong walang laman na chat. Kapag sumagot na ang staff, lalabas ang usapan sa Live Chat sa menu at makakasagot ka doon.',
  },
  {
    keywords: [
      'account', 'profile', 'login', 'log in', 'mag-log in', 'sign in', 'google',
      'password', 'magpalit ng password', 'contact number ko', 'profile ko',
      'i-update ang profile', 'update profile', 'delete account',
      'burahin ang account', 'my information', 'aking impormasyon',
    ],
    answer:
      'Your profile details come from your Google sign-in. To manage them, open Account Settings — corrections are shared from your Google account, and you can manage account options (including account deletion) there.',
    answerTagalog:
      'Ang iyong profile ay mula sa iyong Google sign-in. Para pamahalaan ito, buksan ang Account Settings — ang mga pagwawasto ay mula sa iyong Google account, at maaari mong pamahalaan ang account options (kasama ang pag-delete ng account) doon.',
  },
  {
    keywords: [
      'install', 'home screen', 'i-install', 'app sa phone', 'gamitin ang app',
      'download app', 'mobile app',
    ],
    answer:
      'The portal runs in your phone browser — there is no app-store download. To use it like an app, open it in Chrome or Safari and choose "Add to Home Screen" from the browser menu to add a shortcut on your phone.',
    answerTagalog:
      'Tumatakbo ang portal sa browser ng iyong phone — walang ida-download sa app store. Para magamit na parang app, buksan ito sa Chrome o Safari at piliin ang "Add to Home Screen" sa menu ng browser para magkaroon ng shortcut sa phone mo.',
  },
  {
    keywords: [
      'notification', 'notifications', 'mga notipikasyon', 'alert', 'bell',
      'unread', 'notify', 'notipikasyon', 'alerto', 'hindi pa nababasa',
    ],
    answer:
      'Notifications show alerts about your document requests, incident reports, and chats. Open Notifications from the menu to see them; the header bell shows your unread count.',
    answerTagalog:
      'Ipinapakita ng Notifications ang mga alerto tungkol sa iyong document requests, incident reports, at chats. Buksan ang Notifications sa menu; ang bell sa header ay nagpapakita ng bilang ng hindi pa nababasa.',
  },
  {
    keywords: [
      'accessibility', 'text size', 'font', 'high contrast', 'display',
      'contrast', 'laki ng text', 'kaibahan',
    ],
    answer:
      'You can adjust text size and enable high contrast under Display & Accessibility in the menu.',
    answerTagalog:
      'Maaari mong baguhin ang laki ng text at i-enable ang high contrast sa Display & Accessibility sa menu.',
  },
  {
    keywords: ['help', 'support', 'faq', 'assist', 'suporta'],
    answer:
      'The Help & Support Center has frequently asked questions and contact options for the barangay administration, including the emergency hotline.',
    answerTagalog:
      'Ang Help & Support Center ay may mga frequently asked questions at contact options para sa barangay administration, kasama ang emergency hotline.',
  },
  {
    keywords: [
      'privacy', 'terms', 'data', 'legal', 'ra 10173', 'consent',
      'pahintulot', 'privacy policy',
    ],
    answer:
      'Your data is handled under the Data Privacy Act of 2012 (RA 10173). See Data Privacy & Terms in the menu for the full policy.',
    answerTagalog:
      'Ang iyong data ay pinangangasiwaan alinsunod sa Data Privacy Act of 2012 (RA 10173). Tingnan ang Data Privacy & Terms sa menu para sa buong patakaran.',
  },
];

/** Authoritative portal guide injected into the system prompt. */
const PORTAL_GUIDE = [
  'DOCUMENT REQUESTS — clearances & certificates. Page: My Document Requests ("/documents").',
  '- Supported types: Barangay Clearance, Certificate of Residency, Certificate of Indigency, Barangay Business Permit, Certificate of Good Moral Character, Barangay ID, and Other.',
  '- To request: open My Document Requests and tap "Request Document". Choose the document type, choose the purpose, enter a contact number and email address, and attach a photo of a valid, government-issued ID (the Verification ID field). Then submit.',
  '- Requirements: document type, purpose, a reachable contact number and email, and a photo of a valid ID.',
  '- Processing: about 2–3 business days; the resident is contacted by phone or email. Processing fees may apply as per barangay ordinance — never quote a specific fee amount. Bring a valid ID when claiming the document at the barangay hall.',
  '- Statuses, in order: Submitted, then Processing, then Ready for Pickup, then Released (or Rejected).',
  '- To track: open My Document Requests and select the request to see its current status and timeline. Notifications also alerts the resident when the status changes.',
  '- A resident cannot approve, release, reject, or cancel a request from the app — barangay staff do that.',
  '',
  'INCIDENT REPORTS & EMERGENCY. Page: My Incident Reports ("/incidents").',
  '- Categories: Fire, Flood, Medical Emergency, Criminal Activity, Road Accident, Domestic Dispute, Infrastructure Damage, Public Disturbance, and Other.',
  '- To report: open My Incident Reports and tap "New Incident Report", choose the category, describe what happened, and set the location on the map. Photos or videos can be attached as evidence.',
  '- The app assigns a triage priority automatically, and barangay responders can open a Live Chat to coordinate with the resident.',
  '- Status and history are tracked in My Incident Reports; Notifications alerts on updates.',
  '- Emergencies: call the barangay emergency hotline or emergency mobile (see "Current barangay information"), or 911 for national emergency services (police, fire, ambulance).',
  '',
  'BARANGAY OFFICIALS. Page: Barangay Officials ("/officials").',
  '- Shows the current Punong Barangay (Barangay Captain), the Kagawad (council members), the SK Chairman, the Barangay Secretary, and the Barangay Treasurer, plus office hours and emergency contacts.',
  '',
  'OFFICE HOURS, ADDRESS & CONTACT. Page: Help & Support Center ("/help").',
  '- Office hours, the barangay hall address, the official email, the telephone/hotline, and the emergency hotline/mobile are shown there and in the "Current barangay information" section.',
  '',
  'ANNOUNCEMENTS, PROGRAMS & NOTICES. Page: Announcements ("/announcements").',
  '- Barangay advisories and programs — medical missions, vaccination, relief/ayuda distribution, curfew, class suspensions — are posted there; the latest ones are also in "Current barangay information".',
  '',
  'PORTAL, ACCOUNT & LIVE CHAT.',
  '- Live Chat ("/chat"): conversations with barangay staff/responders about the resident\'s own requests and reports. A chat is started by barangay staff (after an incident or request), not by the resident — a resident cannot open a new empty chat. Once staff reply, the conversation appears under Live Chat.',
  '- Account Settings ("/account"): profile details come from the resident\'s Google sign-in; account options (including account deletion) are managed there.',
  '- Notifications ("/notifications"): alerts about requests, reports, and chats; the header bell shows the unread count.',
  '- Phone home screen: the portal runs in the phone browser; a resident can add it to the home screen from the browser menu ("Add to Home Screen"). There is no app-store download.',
  '- Display & Accessibility ("/settings"): text size and high-contrast options.',
  '- Data Privacy & Terms ("/legal"): the privacy policy (Data Privacy Act of 2012, RA 10173) and the terms of service.',
  '',
  'Residents sign in with Google, and must accept the terms on first use before accessing the portal.',
].join('\n');

/**
 * System prompt for the hosted model. The live context is appended as a
 * "Current barangay information" section so factual questions are answered
 * from data rather than from the static guide.
 */
function buildSystemPrompt(contextText: string): string {
  const sections = [
    'You are "KaBarangay Assistant", the help assistant inside the KaBarangayConnect resident portal.',
    '',
    'Your job is to answer questions about using the resident portal and the barangay services it provides: document requests (clearances & certificates), incident reporting and emergency contacts, barangay officials, office hours and contact details, announcements and programs, and how to use the portal and account.',
    '',
    'Rules:',
    '1. Stay in scope. Answer only questions about the KaBarangayConnect resident portal and the barangay services it provides. If asked anything unrelated (for example weather, homework, recipes, jokes, or chismis), politely decline and offer to help with the portal instead.',
    '2. Information only. You must never perform actions or change anything on the user\'s behalf. You cannot approve, reject, release, or cancel a document request; cannot delete or edit an incident report; cannot change a status, profile, or contact details; cannot send messages; and cannot start a Live Chat conversation. When asked to do any of these, clearly say you cannot do that, then explain how the user can do it themselves and name the exact page to use.',
    '3. Be accurate and concise. Give the page name and the key steps. Do not invent features, fees, or phone numbers that do not exist. If you are not sure, say you do not know.',
    '4. Use the portal guide below as your source of truth for how to use the portal.',
    '5. Fees and processing. Document requests are processed in about 2–3 business days, a valid ID photo is required, and processing fees may apply as per barangay ordinance — never quote a specific fee amount.',
    '6. Language. Reply in the same language the user writes in. If the user writes in Filipino/Tagalog, reply in Tagalog; if in Cebuano, Ilocano, or another Philippine language, reply in that language; if in English, reply in English. Match the language of the user\'s latest message.',
    '7. Live data. Use the "Current barangay information" section to answer factual questions — e.g. who the barangay captain is, who the officials are, the latest announcements, and contact details. If the answer is not in that section, say you do not know rather than guessing. For anything urgent, give the barangay emergency hotline/mobile and mention 911.',
    '8. Formatting. Light Markdown is welcome and renders correctly in the chat panel: use **bold** for labels, dash bullets for lists, and a short heading only when it helps. Avoid tables and long code blocks — the reply appears in a narrow panel, so keep lines short and replies compact.',
    '',
    'Portal guide:',
    PORTAL_GUIDE,
  ];

  if (contextText) {
    sections.push('', 'Current barangay information:', contextText);
  }

  return sections.join('\n');
}

/** Message shape sent to the hosted model (includes the system turn). */
interface ChatCompletionMessage {
  role: 'system' | 'user' | 'assistant';
  content: string;
}

/** Build the full chat-completion message list from the conversation history. */
function buildMessages(
  history: ChatbotMessage[],
  contextText: string
): ChatCompletionMessage[] {
  return [
    { role: 'system', content: buildSystemPrompt(contextText) },
    ...history,
  ];
}

const TAGALOG_WORDS = [
  'sino', 'ano', 'paano', 'saan', 'kailan', 'bakit', 'magkano', 'ilan',
  'gusto', 'kumuha', 'kuha', 'makakuha', 'kailangan', 'tulong', 'nasaan',
  'kunin', 'ipakita', 'makita', 'anunsyo', 'kapitan', 'kagawad', 'opisyal',
  'pinakabagong', 'gumawa', 'hingi', 'dokumento', 'katibayan', 'sedula',
  'bayad', 'kailan makukuha', 'sinu-sino', 'namumuno', 'bukas', 'oras',
  'lugar', 'opisina', 'numero', 'telepono', 'sabado', 'linggo', 'pabatid',
  'ayuda', 'pamigay', 'bakuna', 'pulong', 'walang pasok', 'kausap',
  'kausapin', 'makausap', 'magpalit', 'notipikasyon', 'sumbong', 'saklolo',
  'sunog', 'baha', 'aksidente', 'krimen', 'nakawan', 'ipaliwanag', 'pwede',
  'paki', 'yung', 'huwag', 'serbisyo',
];

const TAGALOG_PHRASES = [
  'paano mag', 'ano ang', 'sino ang', 'gusto ko', 'saan makikita',
  'paano ba', 'magkano ang', 'pano', 'mag request', 'kailan bukas',
  'saan banda', 'sino po', 'ano po', 'paano po', 'may bayad', 'pwede po',
];

/** Best-effort Tagalog/Filipino detection for the no-key keyword fallback. */
function detectTagalog(text: string): boolean {
  const q = text.toLowerCase();
  if (TAGALOG_PHRASES.some((phrase) => q.includes(phrase))) return true;
  return TAGALOG_WORDS.some(
    (word) => new RegExp(`(^|[^a-z])${word}($|[^a-z])`).test(q)
  );
}

/**
 * Action/mutation requests. The assistant is informational only, so when the
 * user asks it to change data (rather than asking how), the reply is prefixed
 * with an explicit refusal before the topic answer.
 */
const ACTION_REQUEST_PHRASES = [
  'approve my', 'approve the', 'i-approve', 'iapprove', 'reject my',
  'i-reject', 'ireject', 'release my', 'i-release', 'irelease', 'cancel my',
  'i-cancel', 'icancel', 'delete my', 'delete report', 'delete the report',
  'delete my report', 'i-delete', 'idelete', 'burahin ang', 'ipabura',
  'remove my', 'change my status', 'update my status', 'palitan ang status',
  'baguhin ang status', 'process my', 'asikasuhin mo', 'ayusin mo',
  'gawin mo na', 'change my record',
];

const ACTION_VERBS = [
  'approve', 'reject', 'release', 'cancel', 'delete', 'burahin', 'i-update',
  'change', 'edit', 'asikasuhin', 'palitan', 'baguhin',
];

const ACTION_REQUEST_MARKERS = [
  'can you', 'could you', 'would you', 'please', 'paki', 'pwede mo',
  'pwede bang', 'pwede ba', 'pakiusap', 'for me', 'para sa akin', 'mo na',
  'mo ba', 'kaya mo',
];

/** True when the user is asking the assistant to change data (not asking how). */
function isActionRequest(q: string): boolean {
  if (hasKeyword(q, ACTION_REQUEST_PHRASES)) return true;
  return hasKeyword(q, ACTION_VERBS) && hasKeyword(q, ACTION_REQUEST_MARKERS);
}

const ACTION_REFUSAL_ENGLISH =
  'I am an informational assistant, so I cannot change any records for you — I can only explain how you can do it yourself.';
const ACTION_REFUSAL_TAGALOG =
  'Isa akong informational assistant, kaya hindi ako makakapagbago ng anumang record para sa iyo — maipapaliwanag ko lamang kung paano mo ito magagawa mismo.';

function hasKeyword(q: string, keywords: string[]): boolean {
  return keywords.some((keyword) => q.includes(keyword));
}

const CAPTAIN_KEYWORDS = ['captain', 'kapitan', 'punong barangay'];

const OFFICIAL_KEYWORDS = [
  'official', 'officials', 'councilor', 'councilors', 'council', 'kagawad',
  'konsehal', 'opisyal', 'opisyales', 'secretary', 'kalihim', 'treasurer',
  'ingat-yaman', 'sk chairman', 'sk chair', 'sangguniang kabataan', 'namumuno',
  'sinu-sino', 'directory', 'captain', 'kapitan', 'punong barangay',
];

const ANNOUNCEMENT_KEYWORDS = [
  'announcement', 'announcements', 'anunsyo', 'anunsiyo', 'abiso', 'pabatid',
  'pinakabagong', 'balita', 'news', 'bulletin', 'advisory', 'notice',
  'notices', 'public notice', 'ayuda', 'relief', 'pamigay', 'bakuna',
  'vaccination', 'medical mission', 'libreng gamot', 'curfew', 'pulong',
  'walang pasok', 'suspendido ang klase',
];

const BARANGAY_CONTACT_KEYWORDS = [
  'barangay contact', 'barangay hall', 'barangay office', 'barangay phone',
  'contact the barangay', 'kontakin ang barangay', 'tawagan ang barangay',
  'barangay contact number', "barangay's number", 'telepono ng barangay',
  'numero ng barangay', 'address ng barangay', 'saan ang barangay',
  'where is the barangay', 'saan banda', 'saan matatagpuan',
];

const BARANGAY_EMAIL_KEYWORDS = [
  'barangay email', 'email ng barangay', "barangay's email",
  'email address ng barangay', 'official email', 'landline',
];

const OFFICE_HOURS_KEYWORDS = [
  'office hours', 'orario', 'oras ng opisina', 'oras ng barangay',
  'operating hours', 'bukas ang barangay hall', 'bukas ba ang barangay',
  'bukas ba', 'kailan bukas', 'open ba',
];

const EMERGENCY_KEYWORDS = [
  'emergency', 'emergency hotline', 'emergency number', 'emergency mobile',
  'emergency contact', 'emergency contact number', 'numero ng emergency',
  'hotline', 'saklolo', 'tumawag', 'tatawagan', 'sino ang tatawagan',
  'ambulance', 'bumbero', 'tanod', '911',
];

/**
 * Reporting intent. A question that asks how to report an incident belongs to
 * the incident guide, not the emergency-contact card, even when it mentions an
 * emergency-type event (e.g. "how do I report a flood?").
 */
const INCIDENT_INTENT_KEYWORDS = [
  'report', 'i-report', 'ireport', 'mag-report', 'magreport', 'mag-file',
  'file a report', 'filing', 'complaint', 'reklamo', 'sumbong',
  'new incident', 'bagong insidente',
];

/**
 * Compose the barangay contact card for the keyword fallback. Omits fields the
 * live document does not carry (older rows predate the contact fields).
 */
function barangayContactAnswer(
  b: NonNullable<PortalContext['barangay']>,
  tagalog: boolean
): string {
  const lines: string[] = [];
  const locality = [b.city, b.province].filter(Boolean).join(', ');

  if (tagalog) {
    lines.push(`Ang barangay ay ${b.name}${locality ? `, ${locality}` : ''}.`);
    if (b.officeAddress) lines.push(`Barangay hall: ${b.officeAddress}`);
    if (b.contactNumber) lines.push(`Contact number: ${b.contactNumber}`);
    if (b.emailAddress) lines.push(`Email: ${b.emailAddress}`);
    if (b.officeHours && b.officeHours.length > 0)
      lines.push(`Office hours: ${b.officeHours.join('; ')}`);
    if (b.emergencyHotline) lines.push(`Emergency hotline: ${b.emergencyHotline}`);
    if (b.emergencyMobile) lines.push(`Emergency mobile: ${b.emergencyMobile}`);
  } else {
    lines.push(`The barangay is ${b.name}${locality ? `, ${locality}` : ''}.`);
    if (b.officeAddress) lines.push(`Barangay hall: ${b.officeAddress}`);
    if (b.contactNumber) lines.push(`Contact number: ${b.contactNumber}`);
    if (b.emailAddress) lines.push(`Email: ${b.emailAddress}`);
    if (b.officeHours && b.officeHours.length > 0)
      lines.push(`Office hours: ${b.officeHours.join('; ')}`);
    if (b.emergencyHotline) lines.push(`Emergency hotline: ${b.emergencyHotline}`);
    if (b.emergencyMobile) lines.push(`Emergency mobile: ${b.emergencyMobile}`);
  }

  return lines.join('\n');
}

/** Find an official whose position mentions one of the given role hints. */
function findOfficialByRole(
  officials: PortalContext['officials'],
  hints: string[]
): PortalContext['officials'][number] | undefined {
  return officials.find((officer) => {
    const position = officer.designatedPosition.toLowerCase();
    return hints.some((hint) => position.includes(hint));
  });
}

/**
 * Answer factual questions from the live context. Returns null when the
 * question is not a live-data question, so the caller falls back to the static
 * knowledge base.
 */
function liveDataReply(
  q: string,
  context: PortalContext,
  tagalog: boolean
): string | null {
  // "How do I report…" questions belong to the incident guide, even when they
  // mention an emergency-type event — do not short-circuit to the hotline card.
  if (hasKeyword(q, INCIDENT_INTENT_KEYWORDS)) return null;

  // Contact-type questions are checked first so a question like "ano ang
  // emergency mobile number ni Kapitan?" returns the number, not the captain's
  // name.
  const asksForContact =
    hasKeyword(q, BARANGAY_CONTACT_KEYWORDS) ||
    hasKeyword(q, BARANGAY_EMAIL_KEYWORDS) ||
    hasKeyword(q, OFFICE_HOURS_KEYWORDS) ||
    hasKeyword(q, EMERGENCY_KEYWORDS);

  if (asksForContact && context.barangay) {
    return barangayContactAnswer(context.barangay, tagalog);
  }

  const captain = findOfficialByRole(context.officials, [
    'captain',
    'punong barangay',
  ]);

  if (hasKeyword(q, CAPTAIN_KEYWORDS) && captain) {
    return tagalog
      ? `Ang kasalukuyang Barangay Captain ay si ${captain.fullName}.`
      : `The current Barangay Captain is ${captain.fullName}.`;
  }

  // Role-specific lookups (secretary / treasurer / SK) before the full list, so
  // "sino ang secretary" names the person rather than dumping every official.
  const roleLookups: Array<{ keywords: string[]; hints: string[] }> = [
    { keywords: ['secretary', 'kalihim'], hints: ['secretary', 'kalihim'] },
    {
      keywords: ['treasurer', 'ingat-yaman'],
      hints: ['treasurer', 'ingat-yaman'],
    },
    {
      keywords: ['sk chairman', 'sk chair', 'sangguniang kabataan'],
      hints: ['sk chairman', 'sk chair', 'sangguniang kabataan'],
    },
  ];

  for (const role of roleLookups) {
    if (!hasKeyword(q, role.keywords)) continue;
    const officer = findOfficialByRole(context.officials, role.hints);
    if (officer) {
      return tagalog
        ? `Ang kasalukuyang ${officer.designatedPosition} ay si ${officer.fullName}.`
        : `The current ${officer.designatedPosition} is ${officer.fullName}.`;
    }
  }

  if (hasKeyword(q, OFFICIAL_KEYWORDS) && context.officials.length > 0) {
    const list = context.officials
      .map((officer) => `${officer.designatedPosition}: ${officer.fullName}`)
      .join(', ');
    return tagalog
      ? `Ang kasalukuyang mga opisyal ng barangay: ${list}.`
      : `The current barangay officials: ${list}.`;
  }

  if (hasKeyword(q, ANNOUNCEMENT_KEYWORDS) && context.announcements.length > 0) {
    const list = context.announcements
      .map(
        (announcement) =>
          `- ${announcement.titleText}${
            announcement.eventDate ? ` (${announcement.eventDate.slice(0, 10)})` : ''
          }`
      )
      .join('\n');
    return tagalog
      ? `Ito ang mga pinakabagong anunsyo:\n${list}`
      : `Here are the latest announcements:\n${list}`;
  }

  return null;
}

/** Deterministic fallback used when no provider key is configured. */
export function keywordReply(
  userText: string,
  context: PortalContext = EMPTY_CONTEXT
): string {
  const q = userText.toLowerCase();
  const tagalog = detectTagalog(q);

  // Mutation requests are refused up front, then the topic answer explains how
  // the resident can do it themselves.
  const refusal = isActionRequest(q)
    ? tagalog
      ? ACTION_REFUSAL_TAGALOG
      : ACTION_REFUSAL_ENGLISH
    : '';

  const withRefusal = (answer: string) =>
    refusal ? `${refusal}\n\n${answer}` : answer;

  const live = liveDataReply(q, context, tagalog);
  if (live) return withRefusal(live);

  let best: KnowledgeEntry | null = null;
  let bestScore = 0;

  for (const entry of KNOWLEDGE_BASE) {
    const score = entry.keywords.reduce(
      (total, keyword) => (q.includes(keyword) ? total + 1 : total),
      0
    );
    if (score > bestScore) {
      bestScore = score;
      best = entry;
    }
  }

  if (best && bestScore > 0) {
    return withRefusal(
      tagalog && best.answerTagalog ? best.answerTagalog : best.answer
    );
  }

  return withRefusal(
    tagalog
      ? 'Pwede kitang tulungan sa KaBarangayConnect resident portal — gaya ng pag-request ng dokumento (clearance, certificate), pag-report ng insidente at emergency hotline, mga opisyal ng barangay, office hours at address, mga anunsyo at programa, o sa paggamit ng account. Ano ang gusto mong malaman?'
      : 'I can help with the KaBarangayConnect resident portal — for example requesting documents (clearance, certificates), reporting incidents and emergency hotlines, barangay officials, office hours and address, announcements and programs, or using your account. What would you like to know?'
  );
}

/** Build the live portal snapshot from the database. */
export async function buildPortalContext(): Promise<PortalContext> {
  const [barangayDoc, officialDocs, announcementDocs] = await Promise.all([
    Barangay.findOne({ isActive: { $ne: false } }).lean(),
    Official.find({ isDeleted: { $ne: true } })
      .select('fullName designatedPosition contactNumber officeLocation')
      .sort({ createdAt: 1 })
      .lean(),
    Announcement.find({ isHidden: { $ne: true }, isArchived: { $ne: true } })
      .select('titleText eventDate')
      .sort({ createdAt: -1 })
      .limit(5)
      .lean(),
  ]);

  const barangay = barangayDoc
    ? {
        name: barangayDoc.name,
        city: barangayDoc.city,
        province: barangayDoc.province,
        region: barangayDoc.region,
        zipCode: barangayDoc.zipCode,
        contactNumber: barangayDoc.contactNumber,
        emailAddress: barangayDoc.emailAddress,
        officeAddress: barangayDoc.officeAddress,
        officeHours: barangayDoc.officeHours,
        emergencyHotline: barangayDoc.emergencyHotline,
        emergencyMobile: barangayDoc.emergencyMobile,
      }
    : null;

  return {
    barangay,
    officials: officialDocs.map((officer) => ({
      fullName: officer.fullName,
      designatedPosition: officer.designatedPosition,
      contactNumber: officer.contactNumber,
      officeLocation: officer.officeLocation,
    })),
    announcements: announcementDocs.map((announcement) => ({
      titleText: announcement.titleText,
      eventDate: announcement.eventDate
        ? new Date(announcement.eventDate).toISOString()
        : undefined,
    })),
  };
}

/** Render the snapshot into the text block injected into the system prompt. */
function formatPortalContext(context: PortalContext): string {
  const lines: string[] = [];

  if (context.barangay) {
    const b = context.barangay;
    const locality = [b.city, b.province].filter(Boolean).join(', ');
    lines.push(
      `Barangay: ${b.name}${locality ? `, ${locality}` : ''}${
        b.region ? ` (${b.region})` : ''
      }${b.zipCode ? `, ZIP ${b.zipCode}` : ''}.`
    );
    if (b.officeAddress) lines.push(`Barangay hall address: ${b.officeAddress}.`);
    if (b.contactNumber) lines.push(`Barangay contact number: ${b.contactNumber}.`);
    if (b.emailAddress) lines.push(`Barangay email: ${b.emailAddress}.`);
    if (b.officeHours && b.officeHours.length > 0)
      lines.push(`Office hours: ${b.officeHours.join('; ')}.`);
    if (b.emergencyHotline)
      lines.push(`Emergency hotline: ${b.emergencyHotline}.`);
    if (b.emergencyMobile)
      lines.push(`Emergency mobile: ${b.emergencyMobile}.`);
  }

  if (context.officials.length > 0) {
    lines.push('Current officials:');
    for (const officer of context.officials) {
      lines.push(
        `- ${officer.designatedPosition}: ${officer.fullName}${
          officer.contactNumber ? ` (${officer.contactNumber})` : ''
        }`
      );
    }
  }

  if (context.announcements.length > 0) {
    lines.push('Latest announcements:');
    for (const announcement of context.announcements) {
      const date = announcement.eventDate ? announcement.eventDate.slice(0, 10) : '';
      lines.push(`- ${announcement.titleText}${date ? ` (${date})` : ''}`);
    }
  }

  return lines.join('\n');
}

interface ChatCompletionResponse {
  choices?: Array<{ message?: { content?: string } }>;
}

async function callDeepSeek(
  apiKey: string,
  history: ChatbotMessage[],
  contextText: string
): Promise<string> {
  const baseUrl = (process.env.DEEPSEEK_BASE_URL || 'https://api.deepseek.com').replace(/\/+$/, '');
  const model = process.env.DEEPSEEK_MODEL || 'deepseek-chat';

  const res = await fetch(`${baseUrl}/chat/completions`, {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
      Authorization: `Bearer ${apiKey}`,
    },
    body: JSON.stringify({
      model,
      messages: buildMessages(history, contextText),
      temperature: 0.4,
      max_tokens: 500,
    }),
  });

  if (!res.ok) {
    throw new Error(`DeepSeek API error (${res.status}).`);
  }

  const data = (await res.json()) as ChatCompletionResponse;
  const content = data.choices?.[0]?.message?.content;
  if (typeof content !== 'string' || !content.trim()) {
    throw new Error('Empty reply from DeepSeek.');
  }
  return content.trim();
}

async function callHuggingFace(
  apiKey: string,
  model: string,
  history: ChatbotMessage[],
  contextText: string
): Promise<string> {
  const res = await fetch(
    `https://api-inference.huggingface.co/models/${model}/v1/chat/completions`,
    {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        Authorization: `Bearer ${apiKey}`,
      },
      body: JSON.stringify({
        model,
        messages: buildMessages(history, contextText),
        temperature: 0.4,
        max_tokens: 500,
      }),
    }
  );

  if (!res.ok) {
    throw new Error(`Hugging Face API error (${res.status}).`);
  }

  const data = (await res.json()) as ChatCompletionResponse;
  const content = data.choices?.[0]?.message?.content;
  if (typeof content !== 'string' || !content.trim()) {
    throw new Error('Empty reply from Hugging Face.');
  }
  return content.trim();
}

/**
 * Generate the assistant reply for a conversation.
 *
 * Provider and credentials come from environment variables. When the selected
 * provider is not configured, `keywordReply` serves the last user message so
 * the endpoint still returns something useful. `context` is the live portal
 * snapshot injected into the prompt (and the fallback) so factual questions
 * are answered from data.
 */
export async function generateChatReply(
  history: ChatbotMessage[],
  context: PortalContext = EMPTY_CONTEXT
): Promise<string> {
  const contextText = formatPortalContext(context);
  const provider = (process.env.CHATBOT_PROVIDER || 'deepseek').toLowerCase();
  const lastUser = [...history]
    .reverse()
    .find((message) => message.role === 'user');

  if (provider === 'huggingface') {
    const apiKey = process.env.HUGGINGFACE_API_KEY;
    const model = process.env.HUGGINGFACE_MODEL;
    if (apiKey && model) return callHuggingFace(apiKey, model, history, contextText);
    return keywordReply(lastUser?.content ?? '', context);
  }

  // Default (deepseek) and any unknown provider value fall through here.
  const apiKey = process.env.DEEPSEEK_API_KEY;
  if (apiKey) return callDeepSeek(apiKey, history, contextText);
  return keywordReply(lastUser?.content ?? '', context);
}
