/**
 * Resident-portal AI assistant (portal-wide Q&A).
 *
 * Answers are generated by a hosted chat model behind a small provider
 * abstraction:
 *   - `deepseek`    OpenAI-compatible chat completions (default).
 *   - `huggingface` Hugging Face Inference API chat completions.
 *
 * When the selected provider's API key (or required model) is not configured —
 * e.g. local dev before the key is provisioned — the assistant falls back to a
 * keyword matcher over the same knowledge base below, so the feature remains
 * usable and testable without external credentials.
 *
 * The assistant is informational only: it explains how the resident portal
 * works and where to find things, but never performs actions or changes data.
 */

export type ChatbotMessage = {
  role: 'user' | 'assistant';
  content: string;
};

/** Cap on the persisted conversation length (oldest turns are dropped). */
export const CHATBOT_MAX_MESSAGES = 40;

/** Cap on a single user message (characters). */
export const CHATBOT_MAX_MESSAGE_LENGTH = 2000;

/** Knowledge-base entry used by the no-key keyword fallback. */
interface KnowledgeEntry {
  /** Lowercase keyword fragments that indicate the topic. */
  keywords: string[];
  answer: string;
}

/**
 * Portal knowledge base — mirrors the resident sidebar (`ResidentSidebar`) and
 * the resident help FAQ. Used by the keyword fallback; the system prompt below
 * carries the authoritative, full guide for the hosted model.
 */
const KNOWLEDGE_BASE: KnowledgeEntry[] = [
  {
    keywords: [
      'document', 'clearance', 'certificate', 'request document',
      'barangay clearance', 'indigency', 'track document', 'document request',
      'request status', 'ready for pickup', 'my document',
    ],
    answer:
      'You can request documents under My Document Requests. Tap "Request Document", choose the type (e.g. Barangay Clearance), fill in the purpose, and submit. You can then open the request any time to see its status and timeline.',
  },
  {
    keywords: [
      'incident', 'report', 'emergency', 'fire', 'flood', 'accident',
      'report incident', 'new incident', 'crime', 'priority', 'triage',
    ],
    answer:
      'To report an incident, open My Incident Reports and tap "New Incident Report". Choose the category, describe what happened, and set the location. The system assigns a priority, and you can chat with responders from Live Chat.',
  },
  {
    keywords: [
      'chat', 'live chat', 'message', 'talk', 'responder', 'barangay staff',
      'contact barangay',
    ],
    answer:
      'Live Chat lets you talk to barangay staff about your requests and reports. Open Live Chat from the menu; conversations appear there once a staff member replies.',
  },
  {
    keywords: ['announcement', 'news', 'update', 'advisory'],
    answer:
      'Barangay announcements are under Announcements in the menu. Open one to read the full post.',
  },
  {
    keywords: ['official', 'captain', 'councilor', 'barangay officials', 'who'],
    answer:
      'You can see the current barangay officials under Barangay Officials in the menu.',
  },
  {
    keywords: [
      'account', 'profile', 'contact number', 'phone', 'update profile',
      'delete account', 'email', 'my information', 'change my',
    ],
    answer:
      'Your profile details come from your Google sign-in. To change them, open Account Settings — corrections are shared from your Google account, and you can manage account options (including deletion) there.',
  },
  {
    keywords: ['notification', 'alert', 'bell', 'unread', 'notify'],
    answer:
      'Notifications show alerts about your document requests, incident reports, and chats. Open Notifications from the menu to see them; the header bell shows your unread count.',
  },
  {
    keywords: [
      'accessibility', 'text size', 'font', 'high contrast', 'display',
      'contrast',
    ],
    answer:
      'You can adjust text size and enable high contrast under Display & Accessibility in the menu.',
  },
  {
    keywords: ['help', 'support', 'hotline', 'faq', 'assist'],
    answer:
      'The Help & Support Center has frequently asked questions and contact options for the barangay administration, including the emergency hotline.',
  },
  {
    keywords: ['privacy', 'terms', 'data', 'legal', 'ra 10173', 'consent'],
    answer:
      'Your data is handled under the Data Privacy Act of 2012 (RA 10173). See Data Privacy & Terms in the menu for the full policy.',
  },
];

/** Authoritative portal guide injected into the system prompt. */
const PORTAL_GUIDE = [
  '- Dashboard ("/"): an overview of your document requests, incident reports, chats, and announcements.',
  '- My Document Requests ("/documents"): request Barangay Clearance or other certificates, fill in the purpose, and track each request\'s status and timeline.',
  '- My Incident Reports ("/incidents"): file a report (category, description, location), see its assigned priority and status, and chat with responders.',
  '- Live Chat ("/chat"): talk to barangay staff about your requests and reports.',
  '- Announcements ("/announcements"): read barangay announcements.',
  '- Barangay Officials ("/officials"): see the current barangay officials.',
  '- Account Settings ("/account"): view your profile (from Google sign-in) and manage your account.',
  '- Notifications ("/notifications"): alerts about your requests, reports, and chats.',
  '- Display & Accessibility ("/settings"): text size and high-contrast options.',
  '- Help & Support Center ("/help"): frequently asked questions and barangay contact options.',
  '- Data Privacy & Terms ("/legal"): the privacy policy and terms of service.',
  '',
  'Residents sign in with Google, and must accept the terms on first use before accessing the portal.',
].join('\n');

const SYSTEM_PROMPT = [
  'You are "KaBarangay Assistant", the help assistant inside the KaBarangayConnect resident portal.',
  '',
  'Your job is to answer questions about using the resident portal: its features, how to do things, and where to find them.',
  '',
  'Rules:',
  '1. Stay in scope. Answer only questions about the KaBarangayConnect resident portal and the barangay services it provides. If asked anything unrelated, politely decline and offer to help with the portal instead.',
  '2. Information only. You must never perform actions or change anything on the user\'s behalf. You cannot submit requests, edit profiles, change contact details, send messages, change settings, or delete accounts. Instead, explain how the user can do it themselves and name the exact page to use.',
  '3. Be accurate and concise. Give the page name and the key steps. Do not invent features that do not exist.',
  '4. Use the portal guide below as your source of truth.',
  '',
  'Portal guide:',
  PORTAL_GUIDE,
].join('\n');

/** Message shape sent to the hosted model (includes the system turn). */
interface ChatCompletionMessage {
  role: 'system' | 'user' | 'assistant';
  content: string;
}

/** Build the full chat-completion message list from the conversation history. */
function buildMessages(history: ChatbotMessage[]): ChatCompletionMessage[] {
  return [{ role: 'system', content: SYSTEM_PROMPT }, ...history];
}

/** Deterministic fallback used when no provider key is configured. */
export function keywordReply(userText: string): string {
  const q = userText.toLowerCase();
  let best: KnowledgeEntry | null = null;
  let bestScore = 0;

  for (const entry of KNOWLEDGE_BASE) {
    const score = entry.keywords.reduce(
      (total, keyword) => (q.includes(keyword) ? total + 1 : total),
      0
    );
    if (score > bestScore) {
      bestScore = score;
      best = entry;
    }
  }

  if (best && bestScore > 0) return best.answer;

  return 'I can help with the KaBarangayConnect resident portal — for example requesting documents, reporting incidents, reading announcements, or account settings. What would you like to know?';
}

interface ChatCompletionResponse {
  choices?: Array<{ message?: { content?: string } }>;
}

async function callDeepSeek(
  apiKey: string,
  history: ChatbotMessage[]
): Promise<string> {
  const baseUrl = (process.env.DEEPSEEK_BASE_URL || 'https://api.deepseek.com').replace(/\/+$/, '');
  const model = process.env.DEEPSEEK_MODEL || 'deepseek-chat';

  const res = await fetch(`${baseUrl}/chat/completions`, {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
      Authorization: `Bearer ${apiKey}`,
    },
    body: JSON.stringify({
      model,
      messages: buildMessages(history),
      temperature: 0.4,
      max_tokens: 500,
    }),
  });

  if (!res.ok) {
    throw new Error(`DeepSeek API error (${res.status}).`);
  }

  const data = (await res.json()) as ChatCompletionResponse;
  const content = data.choices?.[0]?.message?.content;
  if (typeof content !== 'string' || !content.trim()) {
    throw new Error('Empty reply from DeepSeek.');
  }
  return content.trim();
}

async function callHuggingFace(
  apiKey: string,
  model: string,
  history: ChatbotMessage[]
): Promise<string> {
  const res = await fetch(
    `https://api-inference.huggingface.co/models/${model}/v1/chat/completions`,
    {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        Authorization: `Bearer ${apiKey}`,
      },
      body: JSON.stringify({
        model,
        messages: buildMessages(history),
        temperature: 0.4,
        max_tokens: 500,
      }),
    }
  );

  if (!res.ok) {
    throw new Error(`Hugging Face API error (${res.status}).`);
  }

  const data = (await res.json()) as ChatCompletionResponse;
  const content = data.choices?.[0]?.message?.content;
  if (typeof content !== 'string' || !content.trim()) {
    throw new Error('Empty reply from Hugging Face.');
  }
  return content.trim();
}

/**
 * Generate the assistant reply for a conversation.
 *
 * Provider and credentials come from environment variables. When the selected
 * provider is not configured, `keywordReply` serves the last user message so
 * the endpoint still returns something useful.
 */
export async function generateChatReply(
  history: ChatbotMessage[]
): Promise<string> {
  const provider = (process.env.CHATBOT_PROVIDER || 'deepseek').toLowerCase();
  const lastUser = [...history]
    .reverse()
    .find((message) => message.role === 'user');

  if (provider === 'huggingface') {
    const apiKey = process.env.HUGGINGFACE_API_KEY;
    const model = process.env.HUGGINGFACE_MODEL;
    if (apiKey && model) return callHuggingFace(apiKey, model, history);
    return keywordReply(lastUser?.content ?? '');
  }

  // Default (deepseek) and any unknown provider value fall through here.
  const apiKey = process.env.DEEPSEEK_API_KEY;
  if (apiKey) return callDeepSeek(apiKey, history);
  return keywordReply(lastUser?.content ?? '');
}
